package Datenbank;

public enum STORE_PROCEDURE_KONTEXT {

    MITARBEITER_LOESCHEN,
    ZERTIFIKATE_PRO_MITARBEITER,
    KURS_LOESCHEN,
    ZERTIFIKAT_LOESCHEN,
    AUSWERTUNG_MITARBEITER,
    AUSWERTUNG_ZERTIFIKATE,
    AUSWERTUNG_ALLE_KURSE,
    AUSWERTUNG_ZERTIFIKATE_ALLE_MITARBEITER_GUELTIGKEIT,
    AUSWERTUNG_KURS_PRO_MITARBEITER,
    AUSWERTUNG_ZERTIFIKAT_PRO_MITARBEITER,
    AUSWERTUNG_STAMMDATEN_ALLE_MITARBEITER
}
