package DatenSchicht;

public enum STORE_PROCEDURE_KONTEXT {
    MITARBEITER_LOESCHEN,
    ZERTIFIKATE_PRO_MITARBEITER,
    KURS_LOESCHEN,
    ZERTIFIKAT_LOESCHEN,
    AUSWERTUNG_ZERTIFIKATE,
    AUSWERTUNG_ALLE_KURSE,
    AUSWERTUNG_WEITERILDUNG_ALLE_MITARBEITER_ZEITRAUM,
    AUSWERTUNG_ZERTIFIKATE_ALLE_MITARBEITER_GUELTIGKEIT,
    AUSWERTUNG_KURS_PRO_MITARBEITER,
    AUSWERTUNG_ZERTIFIKAT_PRO_MITARBEITER,
    AUSWERTUNG_STAMMDATEN_ALLE_MITARBEITER,
    AUSWERTUNG_BUDGET_ALLE_KOSTENSTELLE,
    AUSWERTUNG_KOSTENSTELLEN_ALLE,
    AUSWERTUNG_KURSE_PRO_ANBIETER_KOSTENSTELLEN_ZEITRAUM,
    AUSWERTUNG_KURSE_PRO_ANBIETER_SELEKTIV_KOSTENSTELLE_ZEITRAUM
}
